Repository linkedin/rest.li, pull requests merged in 2020-02, with the labels that each got.

#165 Add "Migrating from PDSC to PDL" page
  _data/user_guide_navigation.yml
  pdl_migration.md
  pdl_syntax.md
Labels: documentation

#166 Change pdl property encoding logic to not flatten if nested branches > 1
  data/src/main/java/com/linkedin/data/schema/PdlBuilder.java
  data/src/test/java/com/linkedin/data/schema/TestPdlBuilder.java
  data/src/test/java/com/linkedin/data/schema/TestSchemaToPdlEncoder.java
Labels: enhancement

#168 Properly escape union member aliases in PDL
  data/src/main/java/com/linkedin/data/schema/SchemaToPdlEncoder.java
  generator-test/src/test/java/com/linkedin/pegasus/generator/test/pdl/PdlEncoderTest.java
  generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/idl/enums/EscapedSymbols.pdl
  generator-test/src/test/pegasus/com/linkedin/pegasus/generator/test/idl/unions/WithAliases.pdl
Labels: bug

#172 Create .travis.yml
  .travis.yml
Labels: enhancement

#180 Fix the release script, release from tags
  pre-release-check
  prepare-release
  release-version
Labels: bug

#186 Fix prepare-release script so that tag is deleted on failed push
  prepare-release
Labels: bug

#195 Add check to prepare-release script to prevent branch conflicts
  pre-release-check
  prepare-release
Labels: enhancement
